/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 19.1.7 -fPIC -O3) */

module heichips25_template(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input clk;
  wire clk;
  input ena;
  wire ena;
  input rst_n;
  wire rst_n;
  input [7:0] ui_in;
  wire [7:0] ui_in;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  sg13g2_tiehi _00_ (
    .L_HI(uio_oe[0])
  );
  sg13g2_tiehi _01_ (
    .L_HI(uio_oe[1])
  );
  sg13g2_tiehi _02_ (
    .L_HI(uio_oe[2])
  );
  sg13g2_tiehi _03_ (
    .L_HI(uio_oe[3])
  );
  sg13g2_tiehi _04_ (
    .L_HI(uio_oe[4])
  );
  sg13g2_tiehi _05_ (
    .L_HI(uio_oe[5])
  );
  sg13g2_tiehi _06_ (
    .L_HI(uio_oe[6])
  );
  sg13g2_tiehi _07_ (
    .L_HI(uio_oe[7])
  );
  sg13g2_tielo _08_ (
    .L_LO(uio_out[0])
  );
  sg13g2_tielo _09_ (
    .L_LO(uio_out[1])
  );
  sg13g2_tielo _10_ (
    .L_LO(uio_out[2])
  );
  sg13g2_tielo _11_ (
    .L_LO(uio_out[3])
  );
  sg13g2_tielo _12_ (
    .L_LO(uio_out[4])
  );
  sg13g2_tielo _13_ (
    .L_LO(uio_out[5])
  );
  sg13g2_tielo _14_ (
    .L_LO(uio_out[6])
  );
  sg13g2_tielo _15_ (
    .L_LO(uio_out[7])
  );
  sg13g2_tielo _16_ (
    .L_LO(uo_out[0])
  );
  sg13g2_tielo _17_ (
    .L_LO(uo_out[1])
  );
  sg13g2_tielo _18_ (
    .L_LO(uo_out[2])
  );
  sg13g2_tielo _19_ (
    .L_LO(uo_out[3])
  );
  sg13g2_tielo _20_ (
    .L_LO(uo_out[4])
  );
  sg13g2_tielo _21_ (
    .L_LO(uo_out[5])
  );
  sg13g2_tielo _22_ (
    .L_LO(uo_out[6])
  );
  sg13g2_tielo _23_ (
    .L_LO(uo_out[7])
  );
endmodule
